# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: appstormapp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'appstormapp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ppstormapp.proto\x12\x08\x61ppstorm\"E\n\x12GenerateAppRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\"B\n\x13GenerateAppResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2Y\n\x0b\x61ppstormapp\x12J\n\x0bGenerateApp\x12\x1c.appstorm.GenerateAppRequest\x1a\x1d.appstorm.GenerateAppResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appstormapp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEAPPREQUEST']._serialized_start=31
  _globals['_GENERATEAPPREQUEST']._serialized_end=100
  _globals['_GENERATEAPPRESPONSE']._serialized_start=102
  _globals['_GENERATEAPPRESPONSE']._serialized_end=168
  _globals['_APPSTORMAPP']._serialized_start=170
  _globals['_APPSTORMAPP']._serialized_end=259
# @@protoc_insertion_point(module_scope)
