# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import appstormapp_pb2 as appstormapp__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in appstormapp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppStormServiceStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateApp = channel.unary_unary(
                '/appstorm.AppStormService/GenerateApp',
                request_serializer=appstormapp__pb2.GenerateAppRequest.SerializeToString,
                response_deserializer=appstormapp__pb2.GenerateAppResponse.FromString,
                _registered_method=True)
        self.PublishNFT = channel.unary_unary(
                '/appstorm.AppStormService/PublishNFT',
                request_serializer=appstormapp__pb2.PublishNFTRequest.SerializeToString,
                response_deserializer=appstormapp__pb2.PublishNFTResponse.FromString,
                _registered_method=True)


class AppStormServiceServicer(object):
    """Define the gRPC service
    """

    def GenerateApp(self, request, context):
        """RPC to generate an app
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishNFT(self, request, context):
        """RPC to publish NFT (placeholder)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppStormServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateApp': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateApp,
                    request_deserializer=appstormapp__pb2.GenerateAppRequest.FromString,
                    response_serializer=appstormapp__pb2.GenerateAppResponse.SerializeToString,
            ),
            'PublishNFT': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishNFT,
                    request_deserializer=appstormapp__pb2.PublishNFTRequest.FromString,
                    response_serializer=appstormapp__pb2.PublishNFTResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appstorm.AppStormService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('appstorm.AppStormService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppStormService(object):
    """Define the gRPC service
    """

    @staticmethod
    def GenerateApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appstorm.AppStormService/GenerateApp',
            appstormapp__pb2.GenerateAppRequest.SerializeToString,
            appstormapp__pb2.GenerateAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishNFT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appstorm.AppStormService/PublishNFT',
            appstormapp__pb2.PublishNFTRequest.SerializeToString,
            appstormapp__pb2.PublishNFTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
