# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uiapp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0buiapp.proto\x12\x05uiapp\"$\n\x0ePredictRequest\x12\x12\n\nuser_input\x18\x01 \x01(\t\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2A\n\x05UIApp\x12\x38\n\x07Predict\x12\x15.uiapp.PredictRequest\x1a\x16.uiapp.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uiapp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREDICTREQUEST']._serialized_start=22
  _globals['_PREDICTREQUEST']._serialized_end=58
  _globals['_PREDICTRESPONSE']._serialized_start=60
  _globals['_PREDICTRESPONSE']._serialized_end=93
  _globals['_UIAPP']._serialized_start=95
  _globals['_UIAPP']._serialized_end=160
# @@protoc_insertion_point(module_scope)
